run_name: testrun_small_cdit

# training setup
results_dir: logs
train: True
batch_size: 16
num_workers: 12
model: CDiT-S/2
lr: 8e-5

# normalization for the action space
normalize: True
grad_clip_val: 10.0
context_size: 4

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: -64
  max_dist_cat: 64

# action output params
len_traj_pred: 64

# dataset specific parameters
image_size: 224
datasets:
  recon:
    data_folder: /nfs/turbo/coe-mandmlab/aarapin/recondataset/visualnav-transformer/datasets/recon/
    train: /nfs/turbo/coe-mandmlab/aarapin/recondataset/visualnav-transformer/vint_train/data/data_splits/recon/train/ # path to train folder with traj_names.txt
    test: /nfs/turbo/coe-mandmlab/aarapin/recondataset/visualnav-transformer/vint_train/data/data_splits/recon/train/ # path to test folder with traj_names.txt
    goals_per_obs: 4
